openapi: 3.0.3
info:
  title: Test-BCI
  description: Microservicio backend para manipular información de usuarios
  version: 1.0.0
servers:
  - url: http://localhost:10490
    description: Local Url
paths:
  /users:
    post:
      tags:
        - Users
      summary: Creacion de usuario
      description: Servicio para crear un usuario
      operationId: createUser

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDTO'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRequestDTO'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponseDTO'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponseDTO'
      security:
        - bearerAuth: []

components:
  schemas:
    UserRequestDTO:
      type: object
      properties:
        name:
          type: string
          description: Nombre del usuario
        email:
          type: string
          description: Correo del usuario
        password:
          type: string
          description: Contraseña del usuario
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneDTO'
    PhoneDTO:
      type: object
      properties:
        number:
          type: string
          description: Numero de telefono
        citycode:
          type: string
          description: Codigo de ciudad
        contrycode:
          type: string
          description: Codigo de pais
    ProblemResponseDTO:
      type: object
      properties:
        mensaje:
          type: string
          description: Mensaje de error
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: header
      name: Authorization

  
