/*
 * Test-BCI
 * Microservicio backend para manipular información de usuarios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cl.bci.test.dto;

import cl.bci.test.controller.validator.UserValidation;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Set;

/**
 * UserRequestDTO
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-02T09:56:06.322979-03:00[America/Santiago]")
@UserValidation
public class UserRequestDTO {
  private String name;
  private String email;
  private String password;
  private String token;
  private List<PhoneDTO> phones = null;
}

